# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ctmcViterbi <- function(ts, theta, obs) {
    .Call('_fengyuzHW4_ctmcViterbi', PACKAGE = 'fengyuzHW4', ts, theta, obs)
}

ctmcForwardBackward <- function(ts, theta, obs) {
    .Call('_fengyuzHW4_ctmcForwardBackward', PACKAGE = 'fengyuzHW4', ts, theta, obs)
}

